[package]
name = "mesogenz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
async-openai = "0.20"
tokio = { version = "1.37", features = ["full"] }
